name       : fpc
version    : 3.2.0
release    : 9
source     :
    - https://sourceforge.net/projects/freepascal/files/Source/3.2.0/fpc-3.2.0.source.tar.gz/download : d595b72de7ed9e53299694ee15534e5046a62efa57908314efa02d5cc3b1cf75
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  :
    - programming
    - src : programming
summary    : Free Pascal compiler and toolchain
description: |
    Free Pascal is a free 32/64bit Pascal Compiler. It comes with a run-time library and is fully compatible with Turbo Pascal 7.0 and nearly Delphi compatible. Some extensions are added to the language, like function overloading and generics. Shared libraries can be linked.
    This package contains the command-line compiler and utilities. Provided units are the runtime library (RTL), free component library (FCL) and packages.
strip      : no
libsplit   : no
patterns   :
    - src : /usr/share/fpc
builddeps  :
    - fpc
rundeps    :
    - src : fpc
setup      : |
    %patch -p1 < $pkgfiles/Statelessness-using-the-conventional-path.patch
build      : |
    %make all NOGDB=1
install    : |
    %make_install PREFIX=$installdir/usr
    mv $installdir/usr/lib $installdir/%libdir%
    ln -s %libdir%/fpc/$version/ppcx64 $installdir/usr/bin

    # Install source code.
    install -dm00755 $installdir/usr/share/fpc/src
    cp -a packages rtl $installdir/usr/share/fpc/src

    # Create a configuration file and customize it.
    install -dm00755 $installdir/usr/share/defaults/fpc
    $installdir/%libdir%/fpc/$version/samplecfg $installdir/%libdir%/fpc/$version $installdir/usr/share/defaults/fpc
    # samplecfg prefixes every path with the installation dir... get rid of it.
    find $installdir/usr/share/defaults/fpc -type f -exec sed -E "s|$installdir/{1,2}|/|g" -i {} \;
    # Use -fPIC by default.
    echo -e "\n#ifdef cpux86_64\n# Use -fPIC for x86_64\n-Cg\n#endif" >> $installdir/usr/share/defaults/fpc/fpc.cfg

    # Clean up.
    rm -rf $installdir/usr/share/doc
    # Plenty of empty directories over there.
    find $installdir -type d -empty -delete
