name       : fpc
version    : 3.0.0
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/freepascal/Linux/3.0.0/fpc-3.0.0.x86_64-linux.tar : c952a6f1fc9a32da7a3f77c309e64fa1b536516e4fae16ff58ac10d5ece85dd4
    - http://pilotfiber.dl.sourceforge.net/project/freepascal/Source/3.0.0/fpc-3.0.0.source.tar.gz : 46354862cefab8011bcfe3bc2942c435f96a8958b245c42e10283ec3e44be2dd
license    : GPL-2.0
component  : programming
summary    : FreePascalCompiler and toolchain
description: |
    FreePascalCompiler and toolchain
strip      : no
setup      : |
    %patch -p1 < $pkgfiles/install-sh.patch
    mkdir fpc_bootstrap
    ./install.sh
    tar -xvf $sources/fpc-3.0.0.source.tar.gz
build      : |
    export PATH=$PATH:$workdir/fpc_bootstrap/bin:$workdir/fpc_bootstrap/lib/fpc/3.0.0
    cd fpc-3.0.0/compiler
    fpcmake -Tall
    cd ..
    %make OS_TARGET=linux CPU_TARGET=x86_64 NOGDB=1
install    : |
    export PATH=$PATH:$workdir/fpc_bootstrap/bin:$workdir/fpc_bootstrap/lib/fpc/3.0.0
    cd fpc-3.0.0
    %make_install -j1 PREFIX=$installdir/usr NOGDB=1

    install -d $installdir/etc
    $installdir/usr/lib/fpc/3.0.0/samplecfg $pkgdir/usr/lib/fpc/${pkgver} $installdir/etc
    echo -e "#ifdef cpux86_64\n# for x86_64 use -fPIC by default\n-Cg\n#endif" >> "$installdir/etc/fpc.cfg"
    sed -i "s|lib/$fpcversion|lib/fpc/$fpcversion|" $installdir/etc/fpc.cfg

    ln -s /usr/lib/fpc/3.0.0/ppcx64 $installdir/usr/bin