name       : fpc
version    : 3.0.4
release    : 6
source     :
    - ftp://ftp.freepascal.org/pub/fpc/dist/3.0.4/source/fpc-3.0.4.source.tar.gz : 69b3b7667b72b6759cf27226df5eb54112ce3515ff5efb79d95ac14bac742845
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
component  :
    - programming
    - src : programming
summary    : FreePascalCompiler and toolchain
description: |
    Free Pascal is a free 32/64bit Pascal Compiler. It comes with a
    run-time library and is fully compatible with Turbo Pascal 7.0 and
    nearly Delphi compatible. Some extensions are added to the language,
    like function overloading and generics. Shared libraries can be linked.
    This package contains the command-line compiler and utilities. Provided
    units are the runtime library (RTL), free component library (FCL) and
    packages.
strip      : no
patterns   :
    - src  : /usr/share/fpc
builddeps  :
    - fpc
rundeps    :
    - src  : fpc
setup      : |
    mkdir -p fpc/src
    cp -a packages rtl fpc/src
build      : |
    pushd compiler
        fpcmake -Tall
    popd

    %make OS_TARGET=linux CPU_TARGET=x86_64 NOGDB=1
install    : |
    %make_install -j1 PREFIX=$installdir/usr NOGDB=1

    install -d $installdir/etc
    $installdir/usr/lib/fpc/$version/samplecfg $pkgdir/usr/lib/fpc/$version $installdir/etc
    echo -e "#ifdef cpux86_64\n# for x86_64 use -fPIC by default\n-Cg\n#endif" >> "$installdir/etc/fpc.cfg"
    sed -i "s|lib/$fpcversion|lib/fpc/$fpcversion|" $installdir/etc/fpc.cfg
    sed -i "s|fpc/fpc|fpc|g" $installdir/etc/fpc.cfg

    ln -s /usr/lib/fpc/$version/ppcx64 $installdir/usr/bin
    cp -a fpc $installdir/usr/share
