name       : fpc
version    : 3.0.2
release    : 4
source     :
    - https://sourceforge.net/projects/freepascal/files/Source/3.0.2/fpc-3.0.2.source.tar.gz/download : 67fccddf5da992356f4e90d836444750ce9363608c7db8e38c077f710fcb6258
license    : GPL-2.0
component  : programming
summary    : FreePascalCompiler and toolchain
description: |
    FreePascalCompiler and toolchain
builddeps  :
    - fpc
strip      : no
build      : |
    pushd compiler
    fpcmake -Tall
    popd
    %make OS_TARGET=linux CPU_TARGET=x86_64 NOGDB=1
install    : |
    %make_install -j1 PREFIX=$installdir/usr NOGDB=1

    install -d $installdir/etc
    $installdir/usr/lib/fpc/$version/samplecfg $pkgdir/usr/lib/fpc/$version $installdir/etc
    echo -e "#ifdef cpux86_64\n# for x86_64 use -fPIC by default\n-Cg\n#endif" >> "$installdir/etc/fpc.cfg"
    sed -i "s|lib/$fpcversion|lib/fpc/$fpcversion|" $installdir/etc/fpc.cfg

    ln -s /usr/lib/fpc/$version/ppcx64 $installdir/usr/bin
